### ISSUE TITLE
Toolbar bug and media type and sorting issues

### ISSUE THREAD

**Issue by tolew1** [Mindinventory/Lassi-Android#101]
I have a couple of issues. 

- Is there way to have it Sort by Ascending as a parameter when starting the Activity instead of having the user have to change it themselves every time?
- Also where is the Done or check button? After you select the items how to you finish the activity? All I see is a back button and Sort button. 
- How to you show images, videos and audio files? Even if I set the supported File types it seems to show only images.

**Comment by tolew1** [comment]
> * Also where is the Done or check button? After you select the items how to you finish the activity? All I see is a back button and Sort button.

On this point, the Done button is there but it keeps the color of the SupportToolBar. Whatever color the toolbar is that is the color of the done button so you can't see it. 

This code part doesn't seem to be working.

`menuDone?.icon = changeIconColor(
            this@LassiMediaPickerActivity,
            R.drawable.ic_done_white,
            LassiConfig.getConfig().toolbarResourceColor
        )`

**Comment by vrajendraBhavsar** [comment]
Hello @tolew1,

Thank you for using Lassi! We have released a new version "1.3.0" which you can try out and let us know if the issue still persists on your end.
