### ISSUE TITLE
Library not recognized by android studio 

### ISSUE THREAD

**Issue by HimanshuSatone** [Mindinventory/Lassi-Android#103]
I am using Android studio electric ele with Gradle version 6.5 and Gradle Plugin Version 4.1.3.

When ever I tried to build the the project, it shows the following errors:-

`FAILURE: Build completed with 7 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Mindinventory:Lassi:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
       - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
       - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
     Required by:
         project :app`

I tried using the latest version also but it doesn't make any difference.

**Comment by AshwinN796** [comment]
> I am using Android studio electric ele with Gradle version 6.5 and Gradle Plugin Version 4.1.3.
> 
> When ever I tried to build the the project, it shows the following errors:-
> 
> `FAILURE: Build completed with 7 failures.
> ## 1: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:mergeDebugResources'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 2: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:checkDebugAarMetadata'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 3: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:mergeDebugAssets'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 4: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 5: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:desugarDebugFileDependencies'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 6: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:processDebugMainManifest'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>       ==============================================================================
> 
> 
> ## 7: Task failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:mergeDebugNativeLibs'.
> 
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.Mindinventory:Lassi:1.0.1.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jcenter.bintray.com/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - https://www.jitpack.io/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi-1.0.1.jar
> > - file:/C:/Users/Himanshu/AndroidStudioProjects/singlepoint_android-DevAnil/app/libs/Lassi.jar
> > - https://repo.maven.apache.org/maven2/com/github/Mindinventory/Lassi/1.0.1/Lassi-1.0.1.pom
> > Required by:
> > project :app`
> 
> I tried using the latest version also but it doesn't make any difference.

Upgrade your gradle plugin version to 8.0 and check

**Comment by AshwinN796** [comment]
I resolved this by upgrading gradle plugin version to 8.0.
