### ISSUE TITLE
Help, show crop box in camera preview directly?

### ISSUE THREAD

**Issue by MansonLuo** [Mindinventory/Lassi-Android#105]
Hello, is there a way to move crop box  on top of camera preciew, after click take picture button, it will also crop image

Thanks

**Comment by vrajendraBhavsar** [comment]
Can you please provide some reference UI so we can understand your requirements?

**Comment by MansonLuo** [comment]
hi， like this one
![image](https://github.com/MansonLuo/TemporaryStore/blob/main/aHR0cHM6Ly9pbWcyMDE4LmNuYmxvZ3MuY29tL2Jsb2cvNTk4NTIwLzIwMTkxMC81OTg1MjAtMjAxOTEwMjUxNzQ3MTQ5MDAtMTQ4NjMzNzQ0NS5wbmc.png)

**Comment by MansonLuo** [comment]
Sorry, just click image can see it

**Comment by MansonLuo** [comment]
And, setCropAspectRation(x, y) method doesn't resize the crop box

**Comment by vrajendraBhavsar** [comment]
Hello, thanks for providing the reference. Still, it's not clear enough to understand your issue. Please elaborate your requirements that you're seeking. If you are seeking to crop an image post capturing it through a camera or an image you have selected from media then the functionality of freely resizing the crop box as you pinch or resize is already there. Please try the latest version!

**Comment by MansonLuo** [comment]
thank you have so much patient for my poor English.
My requirement is: after I click take picture button, it will go to camera preview screen that also contain a fixed size crop box and a button used to confirm cropping.
after clicking the crop button, it will crop part of image from camera preview, show the image at home screen.

**Comment by MansonLuo** [comment]
![20190627153355128](https://github.com/Mindinventory/Lassi-Android/assets/19282278/239d77fa-4b19-4708-aaa2-db1dabc11bee)
