### ISSUE TITLE
setCropAspectRation(x, y) method doesn't resize the crop box

### ISSUE THREAD

**Issue by MansonLuo** [Mindinventory/Lassi-Android#106]

**Comment by MansonLuo** [comment]
[image](https://github.com/MansonLuo/TemporaryStore/blob/main/16957215726841245987147617280003.jpg)

**Comment by vrajendraBhavsar** [comment]
Hi @MansonLuo,

Thanks for using the library, I've tried the scenario that you have shown in the image, and cropping functionality as per the provided aspect ratio seems to be working properly in the latest version,

I reckon you are using an older version of this library. Kindly try using the latest library version and let us know if you face any issues. Please find the attachments below which depict the working functionality you are looking for in our library.


![1x1crop](https://github.com/Mindinventory/Lassi-Android/assets/84775226/555db9df-10ac-43cd-bfc4-a0e14b994efb)
![1x4crop](https://github.com/Mindinventory/Lassi-Android/assets/84775226/debd4362-11bb-4f8f-896a-f5fa29c4099d)
![4x1crop](https://github.com/Mindinventory/Lassi-Android/assets/84775226/288a4643-d59e-4824-b116-01f74fae299d)

**Comment by MansonLuo** [comment]
it still didn't work. by the way, I use it with jetpack compose
Here is my project address
[project](https://github.com/MansonLuo/TicketNumberPrint)

Is it possible to use hardwrite position within library ?

**Comment by MansonLuo** [comment]
I run the official sample project on android 33 and 30, the result is same, crop box cannot be resize, and the crop shape didn't appear.
![屏幕截图 2023-09-27 114914](https://github.com/Mindinventory/Lassi-Android/assets/19282278/c2f1f1a1-2946-46aa-a539-56d94a02a8bd)
![屏幕截图 2023-09-27 114843](https://github.com/Mindinventory/Lassi-Android/assets/19282278/69af519b-cefb-4d7f-b14b-a038aa5f7ea5)
