### ISSUE TITLE
Customize sorting UI

### ISSUE THREAD

**Issue by mateustsiqueira** [Mindinventory/Lassi-Android#107]
There's a way to customize UI sorting? (colors and labels - multi language)

![WhatsApp Image 2023-10-11 at 17 09 16](https://github.com/Mindinventory/Lassi-Android/assets/104082735/9822a750-7b5d-4447-98c8-79b7b63d45e4)

**Comment by sanjay-mi** [comment]
Hello @mateustsiqueira 

Thank you for using Lassi. We will provide this customization feature in the upcoming release.

**Comment by vrajendraBhavsar** [comment]
Hello @mateustsiqueira, 

We have rolled out new version 1.4.0 where Customisable Sorting UI feature is available. Two options we are providing for multi-language support.

Option - 1:
- To set language's text programmatically based on the current language set on the device follow below mentioned approach of setting strings in your desired language.
- getMultiLngBuilder() exposes params which you can use to set texts.
```
    val currentLang = Locale.getDefault().language.toString()
    if (currentLang == "es") {
        lassi.getMultiLngBuilder(
            setOkLbl = "d'accord",
            setCancelLbl = "Annuler",
            setSortAscendingLbl = "Ascendant",
            setSortDescendingLbl = "Descendant",
            setSortByDateLbl = "Trier par date"
        )
    }
 ```

Option - 2:
- To localize text content of Lassi picker with multiple language options, define language-specific string resource file in your project and update values of string resource keys mentioned in below link with your desired language.

Refer: 
[Lassi String Resources](https://github.com/Mindinventory/Lassi-Android/blob/931e147ebe6282bd1629858b5a9f29fe5a0b8b32/lassi/src/main/res/values/strings.xml)

For more detail please check readme, 
Thank you!
