### ISSUE TITLE
using this library if i browse photo then latest photo not showing on Top which is capture from camera or download from WhatsApp or something else.

### ISSUE THREAD

**Issue by rajuchoudhary72** [Mindinventory/Lassi-Android#121]
Thank you for using the Lassi Picker library.

The initial loading time may vary depending on the number of images. Upon reopening, it will load much faster. If your device has a large collection of photos, it might take a moment to retrieve all the content. This is the expected behavior of Lassi, similar to how your device's gallery app may take some time to load images.
library version  :- implementation("com.github.Mindinventory:Lassi:1.4.1")
Device Specification :- 
Software / Device Information:

Model: Galaxy A7
OS: One UI 2.0
Android Version: 10
![image (23)](https://github.com/user-attachments/assets/7c4fe9fd-84db-4daf-ad19-76ee4d77889d)

https://github.com/user-attachments/assets/5eb87ac0-e224-4837-811d-4a699ff5ffd8

![WhatsApp Image 2024-10-17 at 10 52 24 AM](https://github.com/user-attachments/assets/c21b2af9-ca06-47a5-9611-7ffecc0a2058)

![image](https://github.com/user-attachments/assets/08e445fb-2038-4ba3-afce-7b06f23f87d8)

**it  needs very urgent  help  .**

**Comment by sanjay-mi** [comment]
Hello @rajuchoudhary72 

We are not able to regenerate the issue. We have tried it on multiple devices. 
Have you checked on another device?

**Comment by sanjay-mi** [comment]
Hello @rajuchoudhary72 

We have released Lassi version 1.4.2! We encourage you to try the latest version, as we’ve made various improvements. We’ve attempted multiple times to reproduce the scenario you described but, unfortunately, have not been able to replicate it. Thank you for your patience and support, and please feel free to reach out if you encounter any issues or need further assistance.
