### ISSUE TITLE
Auto generated file issue AppDatabase_Impl.java 

### ISSUE THREAD

**Issue by hardilundavia** [Mindinventory/Lassi-Android#124]
\data\room\AppDatabase_Impl.java:53: error: onCreate(SupportSQLiteDatabase) in <anonymous com.farefood.cooker.data.room.AppDatabase_Impl$1> cannot override onCreate(SupportSQLiteDatabase) in Delegate
      protected void onCreate(SupportSQLiteDatabase _db) {
                     ^
  attempting to assign weaker access privileges; was public
D:\Gaurav Project\Cooker\app\build\generated\source\kapt\debug\com\farefood\cooker\data\room\AppDatabase_Impl.java:82: error: onValidateSchema(SupportSQLiteDatabase) in <anonymous com.farefood.cooker.data.room.AppDatabase_Impl$1> cannot override onValidateSchema(SupportSQLiteDatabase) in Delegate
      protected RoomOpenHelper.ValidationResult onValidateSchema(SupportSQLiteDatabase _db) {
                                                ^
  attempting to assign weaker access privileges; was public

Unable to update auto generated file methods so I have clean and rebuild , update room version and invalidate cache .
when add library in gradle and try to run app at that time above error faced

**Comment by sanjay-mi** [comment]
Hello @hardilundavia 

Thank you for using Lassi Picker.

Can you please share more details about your issue? 

Could you also give us the details of the below versions?
* Room dependency version
* Lassi picker version
* Android studio version
* Gradle version

**Comment by hardilundavia** [comment]
> Hello @hardilundavia
> 
> Thank you for using Lassi Picker.
> 
> Can you please share more details about your issue?
> 
> Could you also give us the details of the below versions?
> 
> * Room dependency version
> * Lassi picker version
> * Android studio version
> * Gradle version

yes sure

Room version : 2.6.1
Lassi picker version : 1.4.2
Android studio version : Android Studio Ladybug | 2024.2.1 Patch 1 (Build #AI-242.23339.11.2421.12483815, built on October 11, 2024)
Gradle Version : gradle-8.9

**Comment by sanjay-mi** [comment]
Hello @hardilundavia 

We have tried to regenerate the issue but we are not been able to reproduce it. 
I think there is an issue with your AppDatabase class. Please check into that.

**Comment by hardilundavia** [comment]
> Hello @hardilundavia
> 
> We have tried to regenerate the issue but we are not been able to reproduce it. I think there is an issue with your AppDatabase class. Please check into that.

For track that issue what should I have to do ?

**Comment by sanjay-mi** [comment]
Please share your AppDatabase class code.

**Comment by hardilundavia** [comment]
> Please share your AppDatabase class code.

@Database(entities = [DoorEntity::class], version = 1)
abstract class AppDatabase : RoomDatabase() {
    abstract fun doorDao(): DoorDao
}

i have this line in my app database file 
this should affect ? 
This is code in my structure so I need to remove it?

**Comment by sanjay-mi** [comment]
Please check whether your room-generated class's onCreate method is public or not? 
Here I have attached our generated code screenshot

![Screenshot from 2024-11-19 12-07-00](https://github.com/user-attachments/assets/a20da616-666e-4357-8b22-5164f4ad7420)

**Comment by hardilundavia** [comment]
> Please check whether your room-generated class's onCreate method is public or not? Here I have attached our generated code screenshot
> 
> ![Screenshot from 2024-11-19 12-07-00](https://private-user-images.githubusercontent.com/82382452/387527863-a20da616-666e-4357-8b22-5164f4ad7420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzIyODUsIm5iZiI6MTczMjE3MTk4NSwicGF0aCI6Ii84MjM4MjQ1Mi8zODc1Mjc4NjMtYTIwZGE2MTYtNjY2ZS00MzU3LThiMjItNTE2NGY0YWQ3NDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyN2NhZjA4NTVlZTZiY2I2OGFjZTlkNjE3YmZkYWU4ODUwMDc0ZjFhNDUxMDQ4OWViYzYwZjQ5MjI2MzAxZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F3JiEbcpZyMEyILtls2u9ZQ8ZVGqOiMN9zLQW-fMpgY)

Thank you for your help its resolved
