### ISSUE TITLE
All Folder Images,Audio,Video,Documents are not displaying. One suggestion to add limit file size option property for gallery.  

### ISSUE THREAD

**Issue by GrishmaPromact** [Mindinventory/Lassi-Android#20]
I download one video, audio, image so it's in my downloads folder. When I am opening galley using your library I can't able to find download folder image, audio, video and document.

I hope it will be resolved as I'm using your library and facing this issue.

One suggestion to add limit file size option property for gallery.  

Thanks.

**Comment by akashmi** [comment]
@GrishmaPromact good suggestions are always welcome.
we will include it in new version.

**Comment by GrishmaPromact** [comment]
@akashmi Thanks. :) 👍

**Comment by malikmotani** [comment]
Hello @GrishmaPromact ,
Thanks for reporting the issue, our team is looking into it. It would be great for us if you can share the below things to understand the cause properly.
1) Library version 
2) Code snippet
3) Logs if applicable
4) Device specification like (Manufacturer, OS version, etc) 
5) Screenshot/video with steps to reproduce the issue

**Comment by GrishmaPromact** [comment]
Sure.
1. Library version : 0.1.5
2. Code snippet : For video opening

**Comment by malikmotani** [comment]
@GrishmaPromact 
The download folder video length may be more than 30 seconds, you have added 
` .setMinTime(0)
  .setMaxTime(30)`
  
So the library won't show the videos which have longer lengths than 30seconds. Please try to remove these attributes since its optional or increase the max time and check again.

**Comment by GrishmaPromact** [comment]
@malikmotani  video is 30 seconds only. I have verified by my end. 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/20226076/102751524-f1bbd280-438d-11eb-92f7-5e20af85238d.png)
 Attached SS for your reference.

**Comment by malikmotani** [comment]
@GrishmaPromact 
Thanks for the snap, I tried to reproduce your case by downloading the same video sample. And I have found that the video length is 30528 milliseconds (which != 30 seconds) please try with the video which has the length of 30000 milliseconds

**Comment by GrishmaPromact** [comment]
@malikmotani  But in seconds it is displaying 30 seconds. That means video is 30 seconds. So think you need to include that video.

**Comment by malikmotani** [comment]
@GrishmaPromact 
We have added the file size limit feature, please update library version [0.1.6](https://github.com/Mindinventory/Lassi-Android/releases/tag/0.1.6) to use this feature.
