### ISSUE TITLE
Android resource linking failed error on trying to use this library in my project

### ISSUE THREAD

**Issue by sam-androiddev** [Mindinventory/Lassi-Android#21]
Task :app:processDemoDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"C:\\Users\\Sam\\.gradle\\caches\\transforms-2\\files-2.1\\3b9109a8b6ec0a077a300c853b10ac16\\Lassi-0.1.5\\res\\layout\\activity_camera.xml","position":{"startLine":7}}],"original":"C:\\Users\\Sam\\.gradle\\caches\\transforms-2\\files-2.1\\3b9109a8b6ec0a077a300c853b10ac16\\Lassi-0.1.5\\res\\layout\\activity_camera.xml:8: AAPT: error: 'focusWithMarker' is incompatible with attribute cameraGestureTap (attr) enum [autoFocus=1, none=0, takePicture=2] [weak].\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDemoDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Sam\.gradle\caches\transforms-2\files-2.1\3b9109a8b6ec0a077a300c853b10ac16\Lassi-0.1.5\res\layout\activity_camera.xml:8: AAPT: error: 'focusWithMarker' is incompatible with attribute cameraGestureTap (attr) enum [autoFocus=1, none=0, takePicture=2] [weak].

**Comment by malikmotani** [comment]
Hello @sam-androiddev,
Thanks for reporting the issue, our team is looking into it. It would be great for us if you can share the below things to understand the cause properly.

- Library version
- Code snippet
- Logs if applicable
- Device specification like (Manufacturer, OS version, etc)
- Screenshot/video with steps to reproduce the issue

**Comment by sam-androiddev** [comment]
Library version is 0.1.5

**Code snippet is as below:** 
```
Intent videoPicker = new Lassi(getActivity())
                .with(LassiOption.CAMERA_AND_GALLERY)
                .setMaxCount(1)
                .setGridSize(3)
                .setMinTime(15)
                .setMaxTime(30)
                .setMediaType(MediaType.VIDEO)
                .setStatusBarColor(R.color.colorPrimaryDark)
                .setToolbarColor(R.color.colorPrimary)
                .setToolbarResourceColor(android.R.color.white)
                .setProgressBarColor(R.color.colorAccent)
                .setPlaceHolder(R.drawable.ic_image_placeholder)
                .setErrorDrawable(R.drawable.ic_image_placeholder)
                .setSupportedFileTypes("mp4", "mkv", "webm", "avi", "flv", "3gp")
                .build();
        startActivityForResult(videoPicker, RC_VIDEO_PICKER);

```
**I am getting error while trying to run the build:**

> Task :app:processDemoDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"C:\\Users\\Sam\\.gradle\\caches\\transforms-2\\files-2.1\\c6a53b625fc95356ad542abdb50619ed\\jetified-Lassi-0.1.5\\res\\layout\\activity_camera.xml","position":{"startLine":7}}],"original":"C:\\Users\\Sam\\.gradle\\caches\\transforms-2\\files-2.1\\c6a53b625fc95356ad542abdb50619ed\\jetified-Lassi-0.1.5\\res\\layout\\activity_camera.xml:8: AAPT: error: 'focusWithMarker' is incompatible with attribute cameraGestureTap (attr) enum [autoFocus=1, none=0, takePicture=2] [weak].\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDemoDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Sam\.gradle\caches\transforms-2\files-2.1\c6a53b625fc95356ad542abdb50619ed\jetified-Lassi-0.1.5\res\layout\activity_camera.xml:8: AAPT: error: 'focusWithMarker' is incompatible with attribute cameraGestureTap (attr) enum [autoFocus=1, none=0, takePicture=2] [weak].

**Comment by chiragmi** [comment]
Hello @sam-androiddev 
Thank you for sharing the above details. I have tried to regenerate the issue as per your mentioned details but have not been able to get success in that. So can you please check the same with the latest library version and let us know if you will get the same issue.
