### ISSUE TITLE
NullPointerException when using LassiOption.GALLERY

### ISSUE THREAD

**Issue by rossiriccardo21** [Mindinventory/Lassi-Android#30]
When I try to choose an image from the gallery using LassiOption.CAMERA_AND_GALLERY or LassiOption.GALLERY my app crashes with the following error:

` java.lang.NullPointerException: tvFolderName must not be null
        at com.lassi.presentation.mediadirectory.adapter.FolderAdapter$FolderViewHolder.bind(FolderAdapter.kt:44`

This is the code used to invoke the intent:
`val intent = Lassi(a)
                        .with(LassiOption.CAMERA_AND_GALLERY)
                        .setMaxCount(4)
                        .setGridSize(2)
                        .setPlaceHolder(R.drawable.ic_image_placeholder)
                        .setErrorDrawable(R.drawable.ic_image_placeholder)
                        .setStatusBarColor(R.color.colorPrimaryDark)
                        .setToolbarColor(R.color.colorPrimary)
                        .setToolbarResourceColor(android.R.color.white)
                        .setProgressBarColor(R.color.colorAccent)
                        .setCropType(CropImageView.CropShape.OVAL)
                        .setCropAspectRatio(1, 1)
                        .setCompressionRation(10)
                        .setMinFileSize(0)
                        .setMaxFileSize(1000)
                        .enableActualCircleCrop()
                        .setSupportedFileTypes("jpg", "jpeg", "png", "webp", "gif")
                        .enableFlip()
                        .enableRotate()
                        .build()
                    startActivityForResult(intent, 540)`

**Comment by sanjay-mi** [comment]
Hello @rossiriccardo21,
Thanks for reporting the issue, our team is looking into it. It would be great for us if you can share the below things to understand the cause properly.

- Device specification like (Manufacturer, OS version, etc)
- Library version
- Screenshot/video with steps to reproduce the issue

**Comment by rossiriccardo21** [comment]
- Pixel 2 XL with Android 11
- Library version 0.2.0

I  may have found the problem:  I discovered that if I don't call`.setMinFileSize` and `.setMaxFileSize`, or if I set the maximum file size too big, the app crashes.
A new problem arose: when I try to choose images from the gallery, the list of images is empty. If I click on the camera icon, and I take a picture and then I try to choose an image from the gallery again, I can see the pictures in my phone.

**Comment by sanjay-mi** [comment]
Hello @rossiriccardo21,

Thank you for sharing the above details.

I have tried to regenerate the issue as per your mentioned details but not able to get success in that. So can you please provide exact Logcat logs and your implementation details? Also can you please provide the folder structure of your device? that might helpful for me to recreate the scenario.

Please try to run your app on the same configured emulator device and check.

**Comment by chiragmi** [comment]
@rossiriccardo21 
Kindly share details if you’re still facing above-defined issue
