### ISSUE TITLE
Lassi is not importing.

### ISSUE THREAD

**Issue by amitimg29** [Mindinventory/Lassi-Android#32]
Lassi library is not importing to my project after successfully implementation 'com.github.Mindinventory:Lassi:0.2.0' & jetpack.

**Comment by chiragmi** [comment]
Hello @amitimg29 

Thanks for using this library

If you’re getting a **Manifest merger failed with multiple errors** issue then kindly add below defined 2 lines in **gradle.properties** file

`android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true`
