### ISSUE TITLE
How to change selected image/video drawable

### ISSUE THREAD

**Issue by Miteshmakwana73** [Mindinventory/Lassi-Android#33]
currently, it's showing this drawable on image select i wan't to select different selection image how do i change this

in error and place holder we are passing drawable so is there any way to also pass drawable for select image

![Screenshot_1624537420](https://user-images.githubusercontent.com/38969602/123262162-3713b500-d515-11eb-9e44-96f68a113a49.png)

**Comment by akashmi** [comment]
Hi @Miteshmakwana73 
Currently we have not added option to customize image selection icon.
I'm adding this in backlog for next version.

You can fork the library and create PR. contribution from community will be always appreciated. :)

**Comment by Miteshmakwana73** [comment]
@akashmi 

you can update your demo startActivityForResult is deprecated

 ```
 val receieveImageData = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
        val data = it.data
        val resultCode = it.resultCode
        if(resultCode == Activity.RESULT_OK) {
            val selectedMedia =
                data?.getSerializableExtra(KeyUtils.SELECTED_MEDIA) as ArrayList<MiMedia>
            Glide.with(this).load(selectedMedia[0].path).into(imgAvatar)
            Log.e(TAG,"======= ${Gson().toJson(selectedMedia)}")
        }
    }

    val receieveVideoData = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
        val data = it.data
        val resultCode = it.resultCode
        if(resultCode == Activity.RESULT_OK) {
            val selectedMedia =
                data?.getSerializableExtra(KeyUtils.SELECTED_MEDIA) as ArrayList<MiMedia>
            Glide.with(this).load(selectedMedia[0].path).into(imgAvatar)
            Log.e(TAG,"======= ${Gson().toJson(selectedMedia)}")
        }
    }

```

**pass intent like this**
```
//            startActivityForResult(intent, MEDIA_REQUEST_CODE)
 receieveImageData.launch(intent)
```

**Comment by chiragmi** [comment]
Hello @Miteshmakwana73 

Thanks for your suggestion, we’re glad to know that in the below-defined latest version you can customize selected image/video drawable and also updated demo startActivityForResult deprecated code.

`implementation 'com.github.Mindinventory:Lassi:0.2.1'`

Customize selection drawable by
`.setSelectionDrawable(R.drawable.ic_checked_media)`
