### ISSUE TITLE
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor.

### ISSUE THREAD

**Issue by sudarshaana** [Mindinventory/Lassi-Android#35]
Called from fragment and got
`java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.cruxlab.virtuallife/com.lassi.presentation.mediadirectory.LassiMediaPickerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.`

**Comment by chiragmi** [comment]
Hello @sudarshaana 
Thanks for using the library. 

If you’re using an app theme other than **NoActionBar** theme then you get this issue. To resolve that either you have to add below defined 2 attributes in your app theme.
`<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>
`
Or
Use **NoActionBar** theme like,
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
   <item name="colorPrimary">@color/colorPrimary</item>
   <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
   <item name="colorAccent">@color/colorAccent</item>
</style>
`

Please check with the above-defined solution and let us know if you are still facing issues.
