### ISSUE TITLE
App rejected by playstore

### ISSUE THREAD

**Issue by arsalanImtiaz455** [Mindinventory/Lassi-Android#40]
In my app only storage related function is choose file and upload on server ,this library use All storage permission so app rejected on play store cause of android.permission.MANAGE_EXTERNAL_STORAGE this. I sent Google video of where we are using external storage. is there any solution?

Is there possible if we can use this library without this permission?
here is another issue but I didn't get any help #38

**Comment by reena210990** [comment]
> > Currently, we didn't provide support to access other documents without using `android.permission.MANAGE_EXTERNAL_STORAGE` permission.
> > and to access that permission you need to submit a [request to google. ](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en)
> > for now, I'm keeping your suggestion in the backlog for feature updates.
> 
> i requested but they ask me a very solid reason why am i using this and they rejected again

@arsalanImtiaz455 found any solution for this problem?

**Comment by arsalanImtiaz455** [comment]
> 

no @reena210990 I was accessing documents using lassi after many tries I stop using lassi for documents and used another solution.

**Comment by arsalanImtiaz455** [comment]
> > > Currently, we didn't provide support to access other documents without using `android.permission.MANAGE_EXTERNAL_STORAGE` permission.
> > > and to access that permission you need to submit a [request to google. ](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en)
> > > for now, I'm keeping your suggestion in the backlog for feature updates.
> > 
> > 
> > i requested but they ask me a very solid reason why am i using this and they rejected again
> 
> @arsalanImtiaz455 found any solution for this problem?

no @reena210990 I was accessing documents using lassi after many tries I stop using lassi for documents and used another solution.

**Comment by reena210990** [comment]
> > > > Currently, we didn't provide support to access other documents without using `android.permission.MANAGE_EXTERNAL_STORAGE` permission.
> > > > and to access that permission you need to submit a [request to google. ](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en)
> > > > for now, I'm keeping your suggestion in the backlog for feature updates.
> > > 
> > > 
> > > i requested but they ask me a very solid reason why am i using this and they rejected again
> > 
> > 
> > @arsalanImtiaz455 found any solution for this problem?
> 
> no @reena210990 I was accessing documents using lassi after many tries I stop using lassi for documents and used another solution.

@arsalanImtiaz455 can you please help me how to solve this problem?

**Comment by arsalanImtiaz455** [comment]
> > > > > Currently, we didn't provide support to access other documents without using `android.permission.MANAGE_EXTERNAL_STORAGE` permission.
> > > > > and to access that permission you need to submit a [request to google. ](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en)
> > > > > for now, I'm keeping your suggestion in the backlog for feature updates.
> > > > 
> > > > 
> > > > i requested but they ask me a very solid reason why am i using this and they rejected again
> > > 
> > > 
> > > @arsalanImtiaz455 found any solution for this problem?
> > 
> > 
> > no @reena210990 I was accessing documents using lassi after many tries I stop using lassi for documents and used another solution.
> 
> @arsalanImtiaz455 can you please help me how to solve this problem?

yes why not.
can you please tell me exact scenario why you are using MANAGE_EXTERNAL STORAGE ?
are you trying to access documents that's why you are using this permission ?

**Comment by reena210990** [comment]
> In my app only storage related function is choose file and upload on server ,this library use All storage permission so app rejected on play store cause of android.permission.MANAGE_EXTERNAL_STORAGE this. I sent Google video of where we are using external storage. is there any solution?
> 
> Is there possible if we can use this library without this permission? here is another issue but I didn't get any help #38

@arsalanImtiaz455 "In my app only storage related function is choose file and upload on server" for same process I have used lassi

**Comment by reena210990** [comment]
@arsalanImtiaz455 I want to choose pdf file from storage and upload on server.

**Comment by arsalanImtiaz455** [comment]
> @arsalanImtiaz455 I want to choose pdf file from storage and upload on server.

should I send you code that I am using to select PDF ?

**Comment by reena210990** [comment]
@arsalanImtiaz455 Yes please and please tell me now your app accepted by google play store ?

**Comment by arsalanImtiaz455** [comment]
> @arsalanImtiaz455 Yes please and please tell me now your app accepted by google play store ?

yes

**Comment by reena210990** [comment]
> > @arsalanImtiaz455 Yes please and please tell me now your app accepted by google play store ?
> 
> yes

please guide me how to solve and have you used MANAGE_EXTERNAL STORAGE permission in your code?

**Comment by arsalanImtiaz455** [comment]
> @arsalanImtiaz455 Yes please and please tell me now your app accepted by google play store ?

here you can specify what type of document you want to select
private fun browseDocuments() {
        val intent = Intent(Intent.ACTION_OPEN_DOCUMENT)
        intent.addCategory(Intent.CATEGORY_OPENABLE)
        intent.type = "*/*"
        val mimetypes = arrayOf(
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application/vnd.rar", "text/plain", "application/vnd.rar", "application/zip",
            "application/msword", "application/pdf"
        )
        intent.putExtra(Intent.EXTRA_MIME_TYPES, mimetypes)
        startActivityForResult(intent, PICK_FILE_RESPONSE)

    }

**Comment by arsalanImtiaz455** [comment]
> > > @arsalanImtiaz455 Yes please and please tell me now your app accepted by google play store ?
> > 
> > 
> > yes
> 
> please guide me how to solve and have you used MANAGE_EXTERNAL STORAGE permission in your code?

no I removed it from my app's manifest

**Comment by reena210990** [comment]
@arsalanImtiaz455 how to get real path in onActivityResult?

**Comment by reena210990** [comment]
@arsalanImtiaz455 Thank you so much 👍

**Comment by arsalanImtiaz455** [comment]
> @arsalanImtiaz455 Thank you so much 👍

my pleasure 
sorry I was busy.

**Comment by arsalanImtiaz455** [comment]
Thank you for your response
