### ISSUE TITLE
Unable to open camera

### ISSUE THREAD

**Issue by ankit1057** [Mindinventory/Lassi-Android#42]
The camera, when opened keeps on saying that storage permission is not granted even though it is 
![Screenshot_2021-10-25-16-11-22-04_65ddf61950be5104fe4b8fc4e36df261](https://user-images.githubusercontent.com/34769096/138681598-701fde31-f212-4413-b925-3a4336682d32.jpg)

**Comment by Nkgohil007** [comment]
Hello @ankit1057 

Thanks for reporting the issue,

As per my understanding here you have given deny while prompting the runtime permission. So next time you will not get a prompt but you will get this message in the dialog. Here in this scenario, please click on the ok button and you will get redirected to the application permission setting and allow the camera permission.

Thank You.
