### ISSUE TITLE
Crash on reject permissions

### ISSUE THREAD

**Issue by sam3961** [Mindinventory/Lassi-Android#43]
When i reject permission for storage access. App got crashed!!

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1554241952, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.provider.justsaywhat/com.lassi.presentation.mediadirectory.LassiMediaPickerActivity}: android.view.InflateException: Binary XML file line #26 in com.provider.justsaywhat:layout/abc_alert_dialog_material: Binary XML file line #53 in com.provider.justsaywhat:layout/abc_alert_dialog_title_material: Error inflating class androidx.appcompat.widget.DialogTitle

**Comment by sanjay-mi** [comment]
Hello @sam3961 

Thank you for using this library.
We have resolved this issue in lassi version 0.3.0

Thank you
