### ISSUE TITLE
ANR dialog is showing  while fetching folders from your library.

### ISSUE THREAD

**Issue by kinjalsha** [Mindinventory/Lassi-Android#44]
In my app ANR dialog shows while fetching folders .I'm using the latest version of the library.
Thanks

![crash report](https://user-images.githubusercontent.com/85155305/139804474-add7e827-ce0c-47e4-a008-7210005682fd.PNG)
.

**Comment by kinjalsha** [comment]
@chiragmi Is there any update?

**Comment by Nkgohil007** [comment]
Hello @kinjalsha,
Thanks for reporting the issue, our team is looking into it. It would be great for us if you can share the below things to understand the cause properly.

*  Device specification like (Manufacturer, OS version, etc)
*  Library version
*  Screenshot/video with steps to reproduce the issue
*  Please provide the full logs

**Comment by kinjalsha** [comment]
Device specification : 
Xiaomi Mi 10 lite 5G - Android 11 (SDK 30)
Oppo Find X2 Pro - Android 11 (SDK 30)
Xiaomi Mi 11 lite 5G - Android 11 (SDK 30)
Oppo A53 - Android 11 (SDK 30
Redmi Note 10 - Android 11 (SDK 30)
Samsung Galaxy S10+ - Android 11

Library version : Lassi:0.2.2'

Log Details :  Input dispatching timed out (com.lassi.presentation.mediadirectory.LassiMediaPickerActivity, ef28ae4 
![lassi lib](https://user-images.githubusercontent.com/85155305/141468433-6af6e6ae-a1d9-4f64-ac0b-8472aa9d0127.PNG)
/com.lassi.presentation.mediadirectory.LassiMediaPickerActivity (server) is not responding. Waited 8002ms for FocusEvent(hasFocus=true))

**Comment by kinjalsha** [comment]
@Nkgohil007  Is there any update?

**Comment by Ankitsinh-siddhiinfosoft** [comment]
Hey @chiragmi  and @Nkgohil007 is there any patch for above ANR it increasing day by day 

here[https://github.com/Mindinventory/Lassi-Android/blob/master/lassi/src/main/java/com/lassi/presentation/mediadirectory/FolderViewModel.kt] file in which ANR is produced.

**Comment by geeta4** [comment]
on Oppo f19 and RedmiNote 8 pro also has same issue

**Comment by sanjay-mi** [comment]
Hello @kinjalsha , @Ankitsinh-siddhiinfosoft , @geeta4 

Thanks for using this library

We have resolved the issue in latest lassi version 0.3.0

Thank you
