### ISSUE TITLE
ANR - Fetching Folder 

### ISSUE THREAD

**Issue by chiragkhandla1994** [Mindinventory/Lassi-Android#45]
ANR issue on fetching folder issue

**Comment by Nkgohil007** [comment]
Hello @chiragkhandla1994,
Thanks for reporting the issue, our team is looking into it. It would be great for us if you can share the below things to understand the cause properly.

*  Device specification like (Manufacturer, OS version, etc)
*  Library version
*  Screenshot/video with steps to reproduce the issue
*  Provide the full logs

**Comment by sanjay-mi** [comment]
Hello @chiragkhandla1994 

Thanks for using this library

We have resolved the issue in latest lassi version 0.3.0

Thank you
