### ISSUE TITLE
getting crashing 

### ISSUE THREAD

**Issue by annu588** [Mindinventory/Lassi-Android#49]
Unable to start activity ComponentInfo{com.lassi.presentation.mediadirectory.LassiMediaPickerActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by KrutiKamani** [comment]
@annu588 
Thank you for using this library.
 
It would be grate if you will share style which you have given in your AndroidManifest.xml for LassiMediaPickerActivity?

**Comment by sanjay-mi** [comment]
Hello @annu588 

Thanks for using this library

Please use latest lassi version 0.3.0 and let us know in case if you are still facing this issue.

Thank you
