### ISSUE TITLE
Android 12 permission

### ISSUE THREAD

**Issue by mehroshmehboob** [Mindinventory/Lassi-Android#60]
First of all excellent library, i have managed to pick a video from gallery but i tap the top camera icon to make the video directly from camera it shows the dialog to have 
Camera, Audio and/or storage permissions are not granted. Please allow it from setting. [cancel, ok]
tapping ok takes you to the app settings. There all the permissions are allowed but still giving showing this dialog

device name: Samsung a52
Android version : 12
library version : 0.4.0

**Comment by sanjay-mi** [comment]
Hello @mehroshmehboob 

Thank you for using Lassi. 

We have checked your scenario on multiple android 12 devices including Samsung also, but we are not able to regenerate it. Can you please share the video with us? Might be that will helpful for us to regenerate it.

**Comment by Innzes001** [comment]
https://user-images.githubusercontent.com/108512636/176839454-ea7fc43d-4efd-4467-903a-5cc8c2d2a3e6.mp4

please check now

**Comment by sanjay-mi** [comment]
Hello @Innzes001 

I have tried regenerating this issue with Pixel 4A and Samsung S20. But it's not regenerated. 
Here I have attached the video from Pixel 4A. Please check.
https://user-images.githubusercontent.com/82382452/180234862-6cf92b6d-03b1-4fa9-a79d-b2ac44c5449f.mp4

If you are performing a different test case then please share it with us. 

Thank you

**Comment by suyashm002** [comment]
I am also facing the same issue I am using emulator Pixel 4 Tiramisu . Did you find any solution ?
