### ISSUE TITLE
Overlapping lassi toolbar with device statusbar 

### ISSUE THREAD

**Issue by javadghane** [Mindinventory/Lassi-Android#63]
Hi, thanks for this great library. i'm using `lassi v-0.4.0`
When i call lassi for select images the device status bar overlap the toolbar's library, like as this screen shot: 
![image](https://user-images.githubusercontent.com/2885866/180371019-5559b560-5d1f-49d7-9012-d1d152acd5c7.png)

My activity has this flag:
`android:fitsSystemWindows="false"` 
But i need this for my screen. can i override this flag before opening library?

**Comment by chiragmi** [comment]
Hi @javadghane 

Thank you for using the Lassi library.

We've checked that just adding `android:fitsSystemWindows="false"` flag to activity does not affect to status bar transparency. Can you please provide us app theme styles or detail of any programatically theme changes?

**Comment by javadghane** [comment]
Of course, this is my app theme :
`  <style name="AppThemeSimple" parent="Theme.MaterialComponents.DayNight">
        <item name="android:windowNoTitle">true</item>
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimary</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:typeface">monospace</item>
        <item name="colorControlNormal">@color/black</item>
        <item name="titleTextColor">@color/black</item>
        <item name="materialAlertDialogTheme">@style/AlertDialogMaterialTheme</item>
        <item name="colorControlHighlight">@color/colorPrimary</item>
        <item name="android:statusBarColor">@color/colorPrimary</item>
    </style>`

**Comment by suyashm002** [comment]
I am also facing the same issue any solution yet ??

**Comment by chiragmi** [comment]
Hi @javadghane 

Thanks for sharing your app theme. I've checked with the same app theme to set it in the **values** & **values-night** folder and also set the **android:fitsSystemWindows="false"** flag to my activity but still, I'm unable to regenerate it. I'm using version **implementation 'com.github.Mindinventory:Lassi:0.4.0'**. Kindly check the below-attached screenshot of the library after setting this. 

Could you please share the one demo project zip file with your faced issue? It would be better for us to identify the issue.

@suyashm002 Have you also integrated with the same app theme as @javadghane defined above?

![Screenshot_20220829_121714](https://user-images.githubusercontent.com/87471481/187142052-af81cf42-0864-492c-a71b-946de1956ebb.png)

**Comment by javadghane** [comment]
Hi @chiragmi, thanks for taking your time,  
i'm using exact same version `0.4.0`. i thinks its because of another library that i used in my project. thanks for testing, i'll create a new project with same codes and add my libraries one by one to find  the problem and notify you.

**Comment by akashmi** [comment]
@javadghane Thanks for using this lib, appreciated for sharing your feedback. closing this issue as of now. if you still getting the same issue feel free to open a new issue.
