### ISSUE TITLE
How to change the background color of gallery Recyclerview

### ISSUE THREAD

**Issue by irshadir7** [Mindinventory/Lassi-Android#64]
i want change the background color of gallery recycler view into black currently it is white

**Comment by chiragmi** [comment]
Hello @irshadir7 

Thank you for using the Lassi library.

We have released a new version of lassi 1.0.1.
In this version, we have provided this feature. You can use the below-defined function to change the background color of the Gallery.

val intent = Lassi(this)
                    .with(LassiOption.GALLERY)
                    .**setGalleryBackgroundColor(R.color.black)**

Please try it out and let us know in the case have any issues.

Thank you

**Comment by irshadir7** [comment]
Hi
Can we reduce the file while cropping. Can we set limit for file cropping

**Comment by irshadir7** [comment]
Hi,

Kindly Help me resolve this issue.

https://github.com/Mindinventory/Lassi-Android/issues/80

Thanks

**Comment by irshadir7** [comment]
This is your sumsub sdk file

<attr format="enum" name="cameraGestureTap">
    <enum name="none" value="0"/>
    <enum name="autoFocus" value="1"/>
    <enum name="takePicture" value="2"/>
    <enum name="takePictureSnapshot" value="3"/>
</attr>


This is your values file

<attr format="enum" name="cameraGestureTap">
    <enum name="none" value="0"/>
    <enum name="focus" value="1"/>
    <enum name="focusWithMarker" value="2"/>
    <enum name="capture" value="3"/>
</attr>
