### ISSUE TITLE
Disable CAMERA, allow Gallery only for Images or Videos?

### ISSUE THREAD

**Issue by AlexUrrutia** [Mindinventory/Lassi-Android#66]
Is it possible to disable the camera while allowing to choose videos or images from the gallery? I don't want to show the camera option when choosing video or image.
Thanks!

**Comment by chiragmi** [comment]
Hello @AlexUrrutia 

Thank you for using the Lassi library.

We have released a new version of lassi 1.0.1.
In this version, we have provided this feature. You can access only the gallery by using **LassiOption.GALLERY** option.

 val intent = Lassi(this).with(LassiOption.GALLERY) 
 //Here, Options are **CAMERA**, **GALLERY** & **CAMERA_AND_GALLERY** 

Please try it out and let us know in the case have any issues.

Thank you

**Comment by AlexUrrutia** [comment]
Now it works great, thanks a lot!
