### ISSUE TITLE
Can we add support for Image and Video together ?

### ISSUE THREAD

**Issue by mohitmanuja** [Mindinventory/Lassi-Android#72]
Currently, This library gives support for either image or video. Can we add support for both together?

**Comment by mohitmanuja** [comment]
@pratikmi @akashmi @malikmotani @mehulrajput

**Comment by akashmi** [comment]
@mohitmanuja 
We currently support it using the system default file manager as per the attached screenshot. you can add multiple file extensions as per your choice.
Not supported the same function with the customized list. it is in the backlog for a future version. 

<img width="871" alt="Screenshot 2022-09-26 at 12 27 21 PM" src="https://user-images.githubusercontent.com/11882168/192212539-6ca32755-1fdc-4f3a-b89f-211192a87a6e.png">

**Comment by mohitmanuja** [comment]
@akashmi Cool, Thanks for the reply.
