### ISSUE TITLE
Deleted Videos still appear in video picker

### ISSUE THREAD

**Issue by HeshamMorsy** [Mindinventory/Lassi-Android#74]
Hello,
thank you for this great library,
I just have an issue in picking videos.

Steps to produce the issue :
1- open video picker once, the video files is shown successfully.
2- If the user deleted one of the videos inside the gallery and try to pick a video again, the deleted video still appears in the video picker.

Is there is any solution, please ?

**Comment by marawanturky** [comment]
Any updates on this issue?

**Comment by sanjay-mi** [comment]
Hello @HeshamMorsy & @marawanturky 

Thank you for using the Lassi library.

We have released a new version 1.2.0
In this release, we have resolved deleted videos appearing in the video picker.

Thank you
