### ISSUE TITLE
Android resource linking failed error on trying to use this library 

### ISSUE THREAD

**Issue by irshadir7** [Mindinventory/Lassi-Android#80]
Hi ,
I was trying to integrate https://developers.sumsub.com/msdk/android/#getting-started - SAMSUB SDK along with this lazzi lib. but after adding this sum sub SDK i am getting an exception. i can able to use this lib without Samsub sdk .kindly pls help me to fix the issue. 

ERROR:C:\Users\mpirs\.gradle\caches\transforms-3\4d27c0fe11d0389fa5c2df92896b9055\transformed\jetified-Lassi-1.1.0\res\layout\activity_camera.xml:8: AAPT: error: 'focusWithMarker' is incompatible with attribute cameraGestureTap (attr) enum [none=0, autoFocus=1, takePicture=2, takePictureSnapshot=3]. 

   Versions:
    implementation 'com.github.Mindinventory:Lassi:1.1.0'
    implementation "com.sumsub.sns:idensic-mobile-sdk:1.20.5"
    minSdk 21
    compileSdk 32

**Comment by sanjay-mi** [comment]
Hello @irshadir7 

Thank you for using the Lassi library.

We have released a new version 1.2.0
Please try the latest version and let us know whether this issue persists.

Thank you
