### ISSUE TITLE
maxFileSize does not work with crop

### ISSUE THREAD

**Issue by rahulr4** [Mindinventory/Lassi-Android#81]
Hi,

I checked your sourcecode.
maxFileSize is not taken into consideration when cropping is enabled.
I set max file size to 3MB.
Image that gets returned is of 5 MB

**Comment by vrajendraBhavsar** [comment]
Hi @rahulr4, thanks for using our library. Could you please let us know which library version you used where you faced this issue?

**Comment by sanjay-mi** [comment]
Hello @rahulr4 

Thank you for using the Lassi library.

We have released a new version 1.2.0
Please try the latest version and let us know whether this issue persists.

Thank you
