### ISSUE TITLE
max count

### ISSUE THREAD

**Issue by kaankaplan-fgx** [Mindinventory/Lassi-Android#83]
hello doesn't work setMaxCount feature, i cant disable multiple selection for FILE_TYPE_WITH_SYSTEM_VIEW.

**Comment by sanjay-mi** [comment]
Hello @kaankaplan-fgx 

Thank you for using the Lassi library.

Android file system not providing such a feature. But we have given the option like showing an error message after choosing the files. You can try this in the latest Lassi version 1.2.0. For more info please check out the sample of lassi.

Thank you
