### ISSUE TITLE
media is not sorted we get the oldest media first is this possible to sort item and get the latest items first 

### ISSUE THREAD

**Issue by arsalanImtiaz455** [Mindinventory/Lassi-Android#84]

**Comment by vinayakmestri** [comment]
Yes, need sorting feature, When user going opening galley it show older media first...which is invalid because user wants to use recent pictures from camera. User has scroll down at bottom to pick recent image clicked.

**Comment by sanjay-mi** [comment]
Hello @arsalanImtiaz455 & @vinayakmestri 

Thank you for using the Lassi library.

We have given a sorting feature in latest lassi version 1.2.0

Thank you
