### ISSUE TITLE
Positive and Negative Buttons are not shown in Permission Disable Alert 

### ISSUE THREAD

**Issue by DeepakRattan** [Mindinventory/Lassi-Android#87]
When the permission is denied for camera or gallery , positive and negative buttons are not shown in Permission alert dialog. 

<img width="307" alt="Screenshot 2023-01-12 at 6 43 00 PM" src="https://user-images.githubusercontent.com/15645007/212075612-7eefbf11-2704-4698-b6e5-acb374c036f2.png">

Please fix this.

**Comment by sanjay-mi** [comment]
Hello @DeepakRattan 

Thank you for using the Lassi library.

We have fixed this issue in latest lassi version 1.2.0
You can also give colors using the below methods.
```
setAlertDialogNegativeButtonColor(R.color.cherry_red)
setAlertDialogPositiveButtonColor(R.color.emerald_green)

```

Thank you
