### ISSUE TITLE
Recycler View null exception occured

### ISSUE THREAD

**Issue by sharawanan** [Mindinventory/Lassi-Android#91]
` java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.setLayoutManager(androidx.recyclerview.widget.RecyclerView$LayoutManager)' on a null object reference
                                                        	at com.lassi.presentation.docs.DocsFragment.setImageAdapter(DocsFragment.kt:196)`

**Comment by sanjay-mi** [comment]
Hello @sharawanan 

Thank you for reporting the issue. It would be great for us if you can share the below things to understand the cause properly.

* Library version
* Code snippet
* Logs if applicable
* Device specification like (Manufacturer, OS version, etc)
* Screenshot/video with steps to reproduce the issue

We have released the latest Lassi version 1.2.0
You can try the latest version and still, this issue persists then please provide us with the above-mentioned details.

Thank you
