### ISSUE TITLE
Removing Max Time Limit in Video mode

### ISSUE THREAD

**Issue by bhallacharanjit** [Mindinventory/Lassi-Android#92]
How do we remove the max time limit? 
If we donot pass the variable or we pass the negative value, then it automatically picks up the min. duration and stops after that and returns an error Toast. 
Any solution to this would be appreciated.

**Comment by sanjay-mi** [comment]
Hello @bhallacharanjit 

Thank you for using Lassi Library.

As of now, we have an implementation like if we do not pass the max time limit then it will take 10 seconds as default.
Also, We are showing this timer in reverse order while the recording is ongoing. 
If you want to do changes then you can import module in your project and can do the necessary changes as per your requirement.

Thank you
